services:
  db:
    image: mariadb:11
    container_name: guestbook-db
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guestdb
      MYSQL_USER: guestuser
      MYSQL_PASSWORD: guestuserpwd
    networks:
      - guestbook-net

  backend:
    image: xela17/guestbook-back:V1.0
    container_name: guestbook-back
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: guestuser
      DB_PASSWORD: guestuserpwd
      DB_NAME: guestdb
    networks:
      - guestbook-net

  frontend:
    image: xela17/guestbook-front:V1.0
    container_name: guestbook-front
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - guestbook-net

volumes:
  db_data: {}

networks:
  guestbook-net:
    driver: bridge
